goog.provide("module$react$lib$SVGDOMPropertyConfig");
goog.require("module$react$lib$DOMProperty");
var DOMProperty$$module$react$lib$SVGDOMPropertyConfig = module$react$lib$DOMProperty;
var MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig = DOMProperty$$module$react$lib$SVGDOMPropertyConfig.injection.MUST_USE_ATTRIBUTE;
var SVGDOMPropertyConfig$$module$react$lib$SVGDOMPropertyConfig = {Properties:{clipPath:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, cx:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, cy:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, d:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, dx:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, dy:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, fill:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, 
fillOpacity:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, fontFamily:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, fontSize:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, fx:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, fy:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, gradientTransform:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, gradientUnits:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, markerEnd:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, 
markerMid:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, markerStart:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, offset:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, opacity:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, patternContentUnits:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, patternUnits:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, points:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, preserveAspectRatio:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, 
r:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, rx:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, ry:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, spreadMethod:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, stopColor:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, stopOpacity:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, stroke:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, strokeDasharray:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, 
strokeLinecap:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, strokeOpacity:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, strokeWidth:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, textAnchor:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, transform:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, version:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, viewBox:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, x1:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, 
x2:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, x:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, y1:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, y2:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig, y:MUST_USE_ATTRIBUTE$$module$react$lib$SVGDOMPropertyConfig}, DOMAttributeNames:{clipPath:"clip-path", fillOpacity:"fill-opacity", fontFamily:"font-family", fontSize:"font-size", gradientTransform:"gradientTransform", gradientUnits:"gradientUnits", markerEnd:"marker-end", 
markerMid:"marker-mid", markerStart:"marker-start", patternContentUnits:"patternContentUnits", patternUnits:"patternUnits", preserveAspectRatio:"preserveAspectRatio", spreadMethod:"spreadMethod", stopColor:"stop-color", stopOpacity:"stop-opacity", strokeDasharray:"stroke-dasharray", strokeLinecap:"stroke-linecap", strokeOpacity:"stroke-opacity", strokeWidth:"stroke-width", textAnchor:"text-anchor", viewBox:"viewBox"}};
module$react$lib$SVGDOMPropertyConfig = SVGDOMPropertyConfig$$module$react$lib$SVGDOMPropertyConfig;
